import { locations } from "@/data/locations";

export const defaultPlayer = {
  name: "",
  avatar: "",
  points: 0,
  cash: 12000,
  happiness: 50,
  energy: 100,
  currentLocation: "apartment",
  week: 1,
  relationship: {
    isDating: false,
    partner: null,
    dateCount: 0,
    happiness: 0,
    health: 80,
  },
  hooksMastered: {
    useState: 0,
    useEffect: 0,
    useRef: 0,
    useContext: 0,
    useReducer: 0,
    useCallback: 0,
    useMemo: 0,
    useTransition: 0,
    customHooks: 0,
    useId: 0,
    useLayoutEffect: 0,
    useDeferredValue: 0,
    useSyncExternalStore: 0,
    useImperativeHandle: 0,
  },
  nextJsMastered: {
    serverComponents: 0,
    appRouter: 0,
    dataFetching: 0,
    serverlessFunctions: 0,
    routing: 0,
    middleware: 0,
    caching: 0,
    deployment: 0,
    redux: 0,
    browserCompatability: 0,
    unitTesting: 0,
    dynamicImports: 0,
    imageOptimization: 0,
    errorHandling: 0,
    pagination: 0,
    fileuploads: 0,
    apiOrganization: 0,
    serverlessSecurity: 0,
    advancedServerFunctions: 0,
    serverFunctions: 0,
    internationalization: 0,
    edgeRuntime: 0,
    serverActions: 0,
    routeProtection: 0,
  },
  javaScriptMastered: {
    arrays: 0,
    objects: 0,
    functions: 0,
    loops: 0,
    conditionals: 0,
    promises: 0,
    asyncAwait: 0,
    destructuring: 0,
    modules: 0,
    closures: 0,
    prototypes: 0,
    asyncIterators: 0,
    strings: 0,
    templateLiterals: 0,
    eventLoop: 0,
    weakMapWeakSet: 0,
    proxies: 0,
  },
  typeScriptMastered: {
    interfaces: 0,
    types: 0,
    basicTypes: 0,
    functions: 0,
    enums: 0,
    generics: 0,
    typeAssertions: 0,
    typeNarrowing: 0,
    advancedTypes: 0,
    modules: 0,
    tuples: 0,
    decorators: 0,
    typeGuards: 0,
    declarationFiles: 0,
  },
  cssMastered: {
    flexbox: 0,
    tailwindUtilities: 0,
    cssGrid: 0,
    animations: 0,
    responsiveDesign: 0,
    cssVariables: 0,
    pseudoClassesElements: 0,
    tailwindResponsiveUtilities: 0,
    tailwindComponents: 0,
    cssTransforms: 0,
    cssFilters: 0,
    cssClipPath: 0,
    cssBackgrounds: 0,
    cssTypography: 0,
  },
  pythonMastered: {
    lists: 0,
    tuples: 0,
    dictionaries: 0,
    functions: 0,
    loops: 0,
    conditionals: 0,
    classes: 0,
    sets: 0,
    strings: 0,
    exceptions: 0,
    modules: 0,
    decorators: 0,
    fileHandling: 0,
    iteratorsGenerators: 0,
    contextManagers: 0,
    regularExpressions: 0,
    multithreading: 0,
  },
  expressMastered: {
    routes: 0,
    middleware: 0,
    templating: 0,
    staticFiles: 0,
    authentication: 0,
    databaseIntegration: 0,
    restfulApis: 0,
    websockets: 0,
    requestHandling: 0,
    responseFormatting: 0,
    sessionManagement: 0,
    fileUploads: 0,
    securityPractices: 0,
  },
  cSharpMastered: {
    classes: 0,
    async: 0,
    interfaces: 0,
    delegates: 0,
    linq: 0,
    generics: 0,
    events: 0,
    dependencyInjection: 0,
    attributes: 0,
    reflection: 0,
    nullable: 0,
    patternMatching: 0,
    recordTypes: 0,
    stringHandling: 0,
    extensionMethods: 0,
    entityFrameworkCore: 0,
    taskParallelLibrary: 0,
  },
  reactNativeMastered: {
    components: 0,
    navigation: 0,
    lists: 0,
    touchables: 0,
    platform: 0,
    asyncStorage: 0,
    gestures: 0,
    animations: 0,
    redux: 0,
    typescript: 0,
    imageHandling: 0,
    networking: 0,
    pushNotifications: 0,
    performanceOptimization: 0,
  },
  javaMastered: {
    classes: 0,
    encapsulation: 0,
    interfaces: 0,
    arrays: 0,
    collections: 0,
    exceptions: 0,
    generics: 0,
    streams: 0,
    multithreading: 0,
    lambda: 0,
    annotations: 0,
    stringHandling: 0,
    fileIO: 0,
    jdbc: 0,
    reflection: 0,
    concurrencyUtilities: 0,
  },
  cppMastered: {
    gameBasics: 0,
    physicsSimulation: 0, // New subject
    inputHandling: 0, // New subject
    collisionDetection: 0, // New subject
    variables: 0,
    functions: 0,
    classes: 0,
    pointers: 0,
    dynamicMemory: 0,
    templates: 0,
    stateManagement: 0,
    animation: 0,
    audioHandling: 0,
    textRendering: 0,
    particleSystems: 0,
    sceneManagement: 0,
  },
  rental: {
    hasApartment: false,
    lastPaidWeek: null,
    rentAmount: 50,
    rentDue: false,
    missedPayments: 0,
    apartmentTier: "Basic", // Added apartmentTier
  },
  possessions: [], // Added possessions array
};

const initialState = {
  isPlayerSelect: true,
  player: null,
  locations,
  currentScreen: "map",
  gameWon: false,
  isWalking: false,
  targetLocation: null,
  message: null,
};

export default initialState;
